### ISSUE TITLE
Testing Party Bug: Editing Profile Name

### ISSUE THREAD

**Issue by sjeremycohen** [gcivil-nyu-org/team-2-inperson#171]
Environment Information:
**OS** Windows 11
**Browser** - Brave 1.45.127 Chromium 107.0.5304.110 (Extensions Disabled - Private Browser Window)
**Credential Used** - user5@test.com

**Error Encountered**
Editing First Name File: Browser Freeze
If left to time out: Error code: Out of Memory
If killed prematurely: Error code: RESULT_CODE_HUNG

**Reproduction Steps**

1. Log in as user5@test.com
2. Navigate to profile
3. Attempt to enter "User5" into the First Name field

**Comment by Pooja-Codes** [comment]
According to the Team-2 test Doc, 
Test Scenario: Update first **_&_** last name
Make sure you are updating both together! The update button will only appear if you pass the input validation and update both. 

If you considered this and still getting errors, Then can you please tell me which values you were trying for First Name & Last Name? @sjeremycohen

**Comment by sjeremycohen** [comment]
Hi Pooja, please see my reproduction steps: I am not even able to enter the last name, the page freezes when I enter the first name

**Comment by virenmparmar** [comment]
I have also faced the same issue. 

Reproduction steps:
1. Login as user4@test.com
2. Go to profile page
3. In the first name instead of typing, select a name from the browser stored name. 

<img width="1440" alt="1" src="https://user-images.githubusercontent.com/19339493/202862537-2b10369b-7a9a-40e4-87d3-f57548e9532e.png">
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/19339493/202862538-bb040820-4b62-4616-993a-d06060c9a106.png">
<img width="1440" alt="3" src="https://user-images.githubusercontent.com/19339493/202862539-612aa908-68c4-47f7-a702-312f4b5486b1.png">

**Comment by Pooja-Codes** [comment]
Fixing! Thank you! @sjeremycohen @virenmparmar
