### ISSUE TITLE
Student & Parent - Categorize recommended High Schools

### ISSUE THREAD

**Issue by waltage** [gcivil-nyu-org/team-2-inperson#29]
In this epic, Students and Parents will be able to categorize High Schools that Shortlist has recommended for them to review.

**Comment by simaoalicechen** [comment]
**User Stories**

- As a student/parent, I want Shortlist to let me categorize candidate High Schools into lists so that I can better organize the schools that I'm interested in.

- As a student/parent, I want Shortlist to let me manage the name/icons/colors of these lists so that I can visually identify which list is for which purpose

**Acceptance Criteria**

- When the parent/kid see a high school they like, they can drag the profile to one of the three lists.
- The lists can store the high schools selected as long as they do not get removed.
- When a list is formed, the parent/kid can name/color the list.
- The parent/kid can remove schools from the lists they made. 

**Definition of Done**


- The lists can save all the selections the parent/kid made. 
- Parent/Kid can make lists and put names/colors/icons to the lists.
- Parent/Kid can modify the contents of the list.
- Unit tests passed.
- Code reviewed.
- Acceptance criteria met.
