### ISSUE TITLE
Student & Parent - View Personalized Recommendations of High Schools

### ISSUE THREAD

**Issue by waltage** [gcivil-nyu-org/team-2-inperson#3]
In this epic, Shortlist will enable Students and Parents to view and interact with personalized recommendations of High Schools.

**Comment by simaoalicechen** [comment]
**User Stories**

- As a student/parent, I want Shortlist to provide a simple view of each High School, so I can make quick judgements
- As a student/parent, I want Shortlist to let me choose a subset of High School features/dimensions, so that my simplified view shows me what I'm interested in
- As a student/parent, I want Shortlist to provide a detailed view of each High School, so that I can break ties more easily

**Acceptance Criteria**

- The kids can view a simple high school profile on the screen; 
- The kids can view the detailed view of the high schools and decide if they want to drag it to one of the lists.

**Definition of Done**

- The high school card has sufficient information for the kids to make decisions.
- Kids can tap into the detailed high school card to view the information.
- Unit tests passed.
- Code reviewed.
- Acceptance criteria met.
