### ISSUE TITLE
Student - Share Shortlists

### ISSUE THREAD

**Issue by waltage** [gcivil-nyu-org/team-2-inperson#7]
In this Epic, students share their lists they have made with their parents to get feedback and have discussions with their parents.

**Comment by simaoalicechen** [comment]
**User Stories**

- As a student, I want Shortlist to Share my chosen lists with parents, so that my parents and I are on the same page with what I want from a high school

**Acceptance Criteria**

- The kids can share the lists they made with the parent account associated with the kids.
- Parents can view the full lists shared by the kids. 

**Definition of Done**

- The lists have all the selections the parent/kid made. 
- Unit tests passed.
- Code reviewed.
- Acceptance criteria met.
